"""create initial database tables

Revision ID: dc3a8adb81c7
Revises:
Create Date: 2026-10-08 21:44:11.040251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "dc3a8adb81c7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "machines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("equipment_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_machines_name"), "machines", ["name"], unique=False)
    op.create_table(
        "maintenance_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("performed_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_maintenance_records_machine_id"),
        "maintenance_records",
        ["machine_id"],
        unique=False,
    )
    op.create_table(
        "sensor_readings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("air_temperature", sa.Float(), nullable=False),
        sa.Column("process_temperature", sa.Float(), nullable=False),
        sa.Column("rotational_speed", sa.Integer(), nullable=False),
        sa.Column("torque", sa.Float(), nullable=False),
        sa.Column("tool_wear", sa.Integer(), nullable=False),
        sa.Column("measured_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sensor_readings_machine_id"),
        "sensor_readings",
        ["machine_id"],
        unique=False,
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("machine_id", sa.Uuid(), nullable=False),
        sa.Column("sensor_reading_id", sa.Uuid(), nullable=False),
        sa.Column("failure_probability", sa.Float(), nullable=False),
        sa.Column("predicted_failure", sa.Boolean(), nullable=False),
        sa.Column("model_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("predicted_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "failure_probability >= 0 AND failure_probability <= 1",
            name="ck_prediction_probability_range",
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sensor_reading_id"],
            ["sensor_readings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_predictions_machine_id"), "predictions", ["machine_id"], unique=False
    )
    op.create_index(
        op.f("ix_predictions_sensor_reading_id"),
        "predictions",
        ["sensor_reading_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_predictions_sensor_reading_id"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_machine_id"), table_name="predictions")
    op.drop_table("predictions")
    op.drop_index(op.f("ix_sensor_readings_machine_id"), table_name="sensor_readings")
    op.drop_table("sensor_readings")
    op.drop_index(
        op.f("ix_maintenance_records_machine_id"), table_name="maintenance_records"
    )
    op.drop_table("maintenance_records")
    op.drop_index(op.f("ix_machines_name"), table_name="machines")
    op.drop_table("machines")
    # ### end Alembic commands ###
